# Generated by Django 3.1.7 on 2021-04-29 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=75)),
                ('keywords', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.CharField(blank=True, max_length=30)),
                ('aboutus', models.TextField()),
                ('smtpserver', models.CharField(blank=True, max_length=16)),
                ('smtpemail', models.CharField(blank=True, max_length=30)),
                ('smtppassword', models.CharField(blank=True, max_length=15)),
                ('smtpport', models.CharField(blank=True, max_length=5)),
                ('icon', models.ImageField(blank=True, upload_to='images/')),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('linkedin', models.CharField(blank=True, max_length=100)),
                ('youtube', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
