# Generated by Django 3.1.7 on 2021-05-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210502_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactformmessage',
            name='status',
        ),
        migrations.RemoveField(
            model_name='contactformmessage',
            name='subject',
        ),
        migrations.AddField(
            model_name='contactformmessage',
            name='answer',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
