# Generated by Django 3.1.7 on 2021-05-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210502_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformmessage',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Read', 'Read')], default='New', max_length=10),
        ),
    ]
