# Generated by Django 3.1.7 on 2021-07-01 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210701_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='orderNumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(max_length=255),
        ),
    ]
